name: Generate Doxygen Documentation

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Doxygen
      run: sudo apt-get install -y doxygen

    - name: Generate Doxygen Documentation
      run: |
        mkdir -p docs
        doxygen Doxyfile
